//card options
const cardArray = [
    {   name: 'rainbownyancat',
        img: 'rainbownyancat-0'
    },
    {   name: 'rainbownyancat',
        img: 'rainbownyancat-0'
    },
    {  name: 'catwithredballoon',
        img: 'catwithredballoon-0'
    }, 
    {  name: 'catwithredballoon',
        img: 'catwithredballoon-0'
    },
    {   name: 'greycat-0',
        img: 'greycat-0'
    },
    {   name: 'greycat-0',
        img: 'greycat-0'
    },
    {   name: 'meow',
        img: 'meow-0'
    },
    {   name: 'meow',
        img: 'meow-0'
    },
    {   name: 'pinkpoptartcat',
        img: 'pinkpoptartcat-0',
    },
    {   name: 'pinkpoptartcat',
        img: 'pinkpoptartcat-0',
    },
    {   name: 'purplecat',
    img: 'purplecat-0',
    },
    {   name: 'purplecat',
        img: 'purplecat-0',
    },
]